In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns  

In [79]:
df=pd.read_csv('news.csv',encoding='cp1252')
sd=pd.read_csv('news2.csv',encoding='cp1252')


In [91]:
df

STORY  SECTION
0     But the most painful was the huge reversal in ...        3
1     How formidable is the opposition alliance amon...        0
2     Most Asian currencies were trading lower today...        3
3     If you want to answer any question, click on ‘...        1
4     In global markets, gold prices edged up today ...        3
...                                                 ...      ...
7623  Karnataka has been a Congress bastion, but it ...        0
7624  The film, which also features Janhvi Kapoor, w...        2
7625  The database has been created after bringing t...        1
7626  The state, which has had an uneasy relationshi...        0
7627  Virus stars Kunchacko Boban, Tovino Thomas, In...        2

[7628 rows x 2 columns]

In [92]:
X = df['STORY']
y = df['SECTION']

In [93]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [94]:
X = cv.fit_transform(X)


In [95]:
from sklearn.model_selection import train_test_split


In [96]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3,random_state=101)


In [97]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [98]:
nb.fit(X_train,y_train)


MultinomialNB()

In [99]:
predictions = nb.predict(X_test)


In [100]:
from sklearn.metrics import confusion_matrix,classification_report


In [101]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[483   8   2   5]
 [ 10 815   3   5]
 [ 22  18 526   1]
 [  1   2   0 388]]


              precision    recall  f1-score   support

           0       0.94      0.97      0.95       498
           1       0.97      0.98      0.97       833
           2       0.99      0.93      0.96       567
           3       0.97      0.99      0.98       391

    accuracy                           0.97      2289
   macro avg       0.97      0.97      0.97      2289
weighted avg       0.97      0.97      0.97      2289



In [106]:
X2 = sd['STORY']
X2 = cv.transform(X2)
predict=nb.predict(X2)
print(predict)



[1 2 1 ... 1 0 1]


In [107]:
y_test_pred = pd.DataFrame(predict,columns=[   'SECTION'   ])


In [108]:
y_test_pred.to_csv('submission.csv', index=False)
